import os
import pandas as pd
from .base import BaseLoader

class Brian2Loader(BaseLoader):
    """
    Loader for simulated data generated by Brian2 simulator.
    """
    def load(self, file_path: str) -> pd.DataFrame:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Brian2 data file not found: {file_path}")

        print(f"🔄 Loading Brian2 file: {file_path} ...")

        # Read brian2 csv file
        df = pd.read_csv(file_path)

        if 'time_sec' in df.columns:
            df.index = pd.to_timedelta(df['time_sec'], unit='s')
            df = df.drop(columns=['time_sec'])

        print(f"✅ Loaded raw Brian2 data: {df.shape}")
        return df